# Compile stage
FROM golang:1.21.1-alpine3.18 AS build-env
ENV CGO_ENABLED 0
WORKDIR /usr/src/app

# Download and install the Delve debugger.
RUN go install github.com/go-delve/delve/cmd/dlv@v1.21.0

# gops is a command to list and diagnose Go processes currently running on your system.
RUN go install github.com/google/gops@v0.3.19

# pre-cache go dependencies
COPY ./sample_app/go.mod ./sample_app/go.sum ./
RUN go mod download && go mod verify

# ARG here is to make the sha available for use in -ldflags
ARG GIT_SHA

# ENV here makes the sha available via os.Getenv
ENV GIT_SHA=${GIT_SHA}

COPY ./sample_app .
RUN go build -ldflags="-X main.Version=${GIT_SHA}" -gcflags "all=-N -l" -v -o /usr/local/bin/app ./...

ENTRYPOINT ["/bin/sh"]